sudo: false
install: git clone --depth 1 https://github.com/sstephenson/bats.git
script: make test
matrix:
  include:
    - language: generic
      env: PYENV_NATIVE_EXT=
    - language: c
      compiler: gcc
      env: PYENV_NATIVE_EXT=1
    - language: c
      compiler: clang
      env: PYENV_NATIVE_EXT=1
