sudo: false
language: c

addons:
  apt:
    packages:
      - python-virtualenv

env:
  global:
    - VIRTUAL_ENV_BASE=~/virtualenv

matrix:
  include:
    # Stackless

    - env: TESTENV=pypy-5.1.1,pypy-dev DIST=precise TRAVIS_LANG=python PYENV_RPYTHON_VERSION=pypy-5.1.1
      dist: precise
      language: python

    # dies after 10 mins of no activity
    # env: TESTENV=2.7.11,pypy-dev DIST=precise TRAVIS_LANG=generic
    #  dist: precise
    #  language: generic

install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - |
    if [[ "${TESTENV%-*}" == 'ironpython' ]]; then
      echo "binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc none" | sudo tee -a /etc/fstab
      echo ':CLR:M::MZ::/usr/bin/mono:' | sudo tee /proc/sys/fs/binfmt_misc/register
    fi

script:
  - if [[ "$TESTENV" == '' ]]; then make test; fi
  - |
    export PYENV_ROOT=.
    for PYENV_VERSION in ${TESTENV//,/ }; do
      ./bin/pyenv install --verbose "$PYENV_VERSION"
      if [[ -x ./versions/$PYENV_VERSION/bin/python ]]; then
        virtualenv --python=./versions/$PYENV_VERSION/bin/python "$VIRTUAL_ENV_BASE/$PYENV_VERSION"
      fi
      if [[ -f "$VIRTUAL_ENV_BASE/$PYENV_VERSION/bin/activate" ]]; then
        source "$VIRTUAL_ENV_BASE/$PYENV_VERSION/bin/activate"
        python --version
      else
        exit 1
      fi
    done
