sudo: false
language: c

addons:
  apt:
    packages:
      - python-virtualenv

env:
  global:
    - VIRTUAL_ENV_BASE=~/virtualenv

matrix:
  include:
    # Stackless

    - env: TESTENV=3.4-dev DIST=precise
      dist: precise
      language: python

    - env: TESTENV=stackless-dev DIST=precise
      dist: precise
      language: generic

    - env: TESTENV=stackless-3.4.1 DIST=precise
      dist: precise
      language: python

    - env: TESTENV=stackless-3.4.1 DIST=precise
      dist: precise
      language: generic


install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - |
    if [[ "${TESTENV%-*}" == 'ironpython' ]]; then
      echo "binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc none" | sudo tee -a /etc/fstab
      echo ':CLR:M::MZ::/usr/bin/mono:' | sudo tee /proc/sys/fs/binfmt_misc/register
    fi

script:
  - if [[ "$TESTENV" == '' ]]; then make test; fi
  - |
    export PYENV_ROOT=.
    if [[ "$TESTENV" != '' ]]; then
      ./bin/pyenv install "$TESTENV"
      if [[ -x ./versions/$TESTENV/bin/python ]]; then
        virtualenv --python=./versions/$TESTENV/bin/python "$VIRTUAL_ENV_BASE/$TESTENV"
      fi
      if [[ -f "$VIRTUAL_ENV_BASE/$TESTENV/bin/activate" ]]; then
        source "$VIRTUAL_ENV_BASE/$TESTENV/bin/activate"
        python --version
      else
        false
      fi
    fi
