sudo: false
language: c

# virtualenv versions:
# precise: 1.7.1.2
# trusty: 1.11.4
# precise: 12.0.6
# trusty: 13.1.0

addons:
  apt:
    # Note that it is not possible to include `virtualenv` from
    # source `debian-sid`, as pulls in many other debian-sid packages
    # which conflicts with the Ubuntu packages.
    packages:
      - python-pip

env:
  global:
    - VIRTUAL_ENV_BASE=~/virtualenv
    - VIRTUAL_ENV_VERSION_SPEC='<13'

matrix:
  include:
    # Plain bats

    - env: PYENV_NATIVE_EXT=
      addons: false
    - env: PYENV_NATIVE_EXT=1
      addons: false

    # PyPy 3

    - env: TESTENV=pypy3-dev
      dist: precise

    - env:
        - TESTENV=pypy3.3-5.2-alpha1
        - VIRTUAL_ENV_VERSION_SPEC=''
      dist: precise

install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - |
    if [[ "${TESTENV%-*}" == 'ironpython' ]]; then
      echo "binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc none" | sudo tee -a /etc/fstab
      echo ':CLR:M::MZ::/usr/bin/mono:' | sudo tee /proc/sys/fs/binfmt_misc/register
    fi

script:
  - if [[ "$TESTENV" == '' ]]; then make test; fi
  - |
    export PYENV_ROOT=.
    pip install --user --upgrade 'virtualenv'"$VIRTUAL_ENV_VERSION_SPEC"
    virtualenv --version
    for PYENV_VERSION in ${TESTENV//,/ }; do
      ./bin/pyenv install "$PYENV_VERSION"
      if [[ -x ./versions/$PYENV_VERSION/bin/python ]]; then
        ./versions/$PYENV_VERSION/bin/python --version
        if [[ "$VIRTUAL_ENV_ADD_LIB_PATH" == '1' ]]; then
          export LD_LIBRARY_PATH="./versions/$PYENV_VERSION/lib/"
        fi
        virtualenv --python=./versions/$PYENV_VERSION/bin/python "$VIRTUAL_ENV_BASE/$PYENV_VERSION"
      fi
      if [[ -f "$VIRTUAL_ENV_BASE/$PYENV_VERSION/bin/activate" ]]; then
        source "$VIRTUAL_ENV_BASE/$PYENV_VERSION/bin/activate"
        python --version
        pip --version
      else
        exit 1
      fi
      export LD_LIBRARY_PATH=""
    done
