sudo: false
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - bats
matrix:
  include:
    - language: generic
      env: PYENV_NATIVE_EXT=
    - language: c
      compiler: gcc
      env: PYENV_NATIVE_EXT=1
    - language: c
      compiler: clang
      env: PYENV_NATIVE_EXT=1
script:
  - |
    if [ "$PYENV_NATIVE_EXT" == '1' ]; then
      ./src/configure
      make -C src
    fi
  - bats --tap test
  - (cd plugins/python-build && bats --tap test)
